name: download-checkout-workflow-to-runner
on: [push]
jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
          - name: list files before
            run: ls -la
          - uses: actions/checkout@v5
          - name: list files after
            run: ls -la

    download-checkout:
      runs-on: ubuntu-latest
      steps:
        - name: list files before
          run: ls -la
        - name: checkout code
          run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
            git fetch origin
            git checkout main
        - name: list files after
          run: ls -la           