name: Manual Workflow 
on: 
  workflow_dispatch:
    inputs:
        string:
            description: 'A string input'
            required: true
            default: 'Hi Vijay! Welcome to Github Actions manual workflow.'
        environment:
            description: 'Select the environment to run the workflow'
            required: true
            type: choice
            options:
                - Dev
                - UAT
                - production
jobs:
    manual-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Run Manual workflow
              run: |
                echo "The string input is: ${{ inputs.string }}"
                echo "The environment input is: ${{ inputs.environment }}"