name: Status Check Workflow
on: [push]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: sleep 20
            - name: step2
              id: step-2
              run: exit 1
            - name: step3
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo "Step 2 failed, so running step 3"
            - name: Runs on Success
              if: success()
              run: echo "This runs only if all previous steps were successful"
            - name: Run Always
              if: always()
              run: echo "This step runs always"
            - name: Run on Cancelled
              if: cancelled()
              run: echo "This step runs if the job was cancelled"
    job2:
        runs-on: ubuntu-latest
        needs: job1
        if: failure()
        steps:
            - name: step1 for Job2
              run: echo "This is Job 2 and it runs only if Job 1 is successful"
